export const capitals = [
    "CARACAS", 
    "PUERTO AYACUCHO", 
    "BARCELONA", 
    "SAN FERNANDO DE APURE", 
    "MARACAY", 
    "BARINAS", 
    "CIUDAD BOLÍVAR", 
    "VALENCIA", 
    "SAN CARLOS",   
    "TUCUPITA",
    "CORO",
    "SAN JUAN DE LOS MORROS",
    "BARQUISIMETO",
    "MÉRIDA",
    "LOS TEQUES",
    "MATURÍN",
    "LA ASUNCIÓN (ISLA DE MARGARITA)",
    "GUANARE",
    "CUMANÁ",
    "SAN CRISTÓBAL",
    "TRUJILLO",
    "LA GÜAIRA",
    "SAN FELIPE",
    "MARACAIBO",
    "GRAN ROQUE (LOS ROQUES)"
]