export const monuments = [
    "Casa Natal de Simón Bolivar",
    "Tobogán de la Selva",
    "Paseo Colón",
    "Puente María Nieves",
    "Museo-Taller Obras de Dios",
    "Museo Alberto Arvelo Torrealba",
    "Salto Ángel",
    "Monumento a Girardot",
    "Cerro Tiramuto",
    "Delta del Orinocco",
    "Cayos de Morrocoy",
    "Esteros de Camaguán",
    "Monumento Manto de María Divina Pastora",
    "Pico Bolívar",
    "Gran Ferrocarril de Venezuela",
    "Parque Nacional Cueva del Guácharo",
    "Museo Marino de Margarita",
    "Santuario Nacional Nuestra Señora de Coromoto",
    "Monumento al Cristo Rey",
    "Parque Zoológico La Laguna",
    "Virgen de La Paz",
    "Aeropuerto Internacional de Maiquetía Simón Bolívar",
    "Reserva Ecológica Guáquira",
    "Puente General Rafael Urdaneta",
    "Sitio Arqueológico La Orchila"
]