export const states = [
    "DISTRITO CAPITAL",
    "AMAZONAS",
    "ANZOATEGUI",
    "APURE",
    "ARAGUA",
    "BARINAS",
    "BOLÍVAR",
    "CARABOBO",
    "COJEDES",
    "DELTA AMACURO",
    "FALCÓN",
    "GUÁRICO",
    "LARA",
    "MÉRIDA",
    "MIRANDA",
    "MONAGAS",
    "NUEVA ESPARTA",
    "PORTUGUESA",
    "SUCRE",
    "TÁCHIRA",
    "TRUJILLO",
    "VARGAS",
    "YARACUY",
    "ZULIA",
    "DEPENDECIAS FEDERALES"
]